### ISSUE TITLE
How to get message scheme?

### ISSUE THREAD

**Issue by pashkatrick** [wesky93/grpc_requests#21]
**Is your feature request related to a problem? Please describe.**
i can get services, methods, but can't get message scheme to build request and send it via reflection

**Describe the solution you'd like**
like Postman's "use example message"

**Comment by ViridianForge** [comment]
When you say "like Postman's 'use example message'" @pashkatrick - are you also envisioning the message to be autopopulated with fake inputs like Postman and Kreya do?

**Comment by pashkatrick** [comment]
it's not necessarily, it would great just like to get the required fields

**Comment by ViridianForge** [comment]
I'll have a think on how to implement that - and see if I can pick it up when I get some free time. Thanks for the suggestion!

**Comment by wesky93** [comment]
@pashkatrick 
It's been a while since I've used postman, so I don't have an exact understanding of its capabilities.
Could you please share a screenshot or sample code of what you're looking for?

**Comment by pashkatrick** [comment]
@wesky93 i think, the better way is download latest postman and check, how it works with grpc

**Comment by ViridianForge** [comment]
@wesky93 here's a screenshot of a message generated by Postman based off reflection against the sample server we've got in the repo.

![image](https://github.com/wesky93/grpc_requests/assets/8301040/e6c2c965-8643-4d1f-8743-b8b13aef240b)

I _think_ what @pashkatrick would like to be able to do is get a list of required (and maybe optional as well) fields from the methods being assembled by reflection.

**Comment by ViridianForge** [comment]
A simple first stab at this is started here: https://github.com/wesky93/grpc_requests/pull/23

Unfortunately, my day job has kept me pretty busy as of late, but I'd like to explore adding a util method to generate example messages in the future - along with better support behind repeated fields and other aspects.
