### ISSUE TITLE
Deprecated method used in `aio.AsyncClient`

### ISSUE THREAD

**Issue by UpstreamData** [wesky93/grpc_requests#29]
**Describe the bug**
When using the `AsyncClient`, a `UserWarning` is issued for a deprecated method.

`UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.`

The issue is originating from -https://github.com/wesky93/grpc_requests/blob/999d00a6c3bcf98aae3a3d2c17e479489ead5b47/src/grpc_requests/aio.py#L198-L199

This would be a drop in replacement with `google.protobuf.message_factory.GetMessageClass()` if it weren't for this line -https://github.com/wesky93/grpc_requests/blob/999d00a6c3bcf98aae3a3d2c17e479489ead5b47/src/grpc_requests/aio.py#L42

Which appears to allow a user to pass a custom symbol database in.

Can this be directly swapped out for the `message_factory`, or does there need to be consideration taken for replacing the symbol database the user can pass in?

**Comment by ViridianForge** [comment]
Thanks for calling this out so thoroughly @UpstreamData - I think this could be resolving by copying over similar logic as is being used in the main client to handle a similar deprecation issue.

When I get some free time, I'll try and get a PR up for that.

**Comment by ViridianForge** [comment]
@UpstreamData - some changes to the `aio.py` file were merged to `Develop` in #31 , so this issue should be fixed in the next release.

Will leave the issue open until then.

**Comment by ViridianForge** [comment]
Version [0.1.12](https://pypi.org/project/grpc-requests/) including a fix for this issue has been released. Thanks again for bringing it to our attention!
