### ISSUE TITLE
request with cookie

### ISSUE THREAD

**Issue by LoeLoveRoob** [wesky93/grpc_requests#30]
i wanna send some requests to a website but that website require to login first how can i define my  cookie in requests that i wanna send?

**Comment by ViridianForge** [comment]
For context, I'm making the assumption that you'll need to use a Cookie header to send your cookie. 

When you create a channel - and when you submit requests through your opened channel to end points, you can attach a list of metadata to your request using a metadata parameter.

I use JWTs in a lot of the requests I make through the library - so hopefully a rough psuedo-code example of that will help you out.

```
request = {'field1':'value1',...}
auth_metadata = [{'authorization',f'bearer {generate_jwt()}]

client.request(
   "SAMPLE_SERVICE",
   "SAMPLE_METHOD",
   request,
   metadata=auth_metadata,
   timeout=10
)
```

**Comment by rlancer** [comment]
this worked for me `metadata=(("authorization", f"bearer {token}"),)`
