### ISSUE TITLE
metadata keyword argument not respected by get_by_endpoint()

### ISSUE THREAD

**Issue by OCDolan** [wesky93/grpc_requests#37]
**Describe the bug**
metadata not respected by get_by_endpoint()

When trying to connect to a grpc server that requires a bearer token, I get a response as below...
`
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "RBAC: access denied"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"RBAC: access denied", grpc_status:7, created_time:"2023-11-27T11:59:49.7471035+00:00"}"
`

**To Reproduce**
Following the example to use a bearer token in https://github.com/wesky93/grpc_requests/blob/master/src/examples/README.md
it looks like the `metadata` keyword argument is not consumed by any `__init__` method in the creation of the `Client` Object

**Expected behavior**
The bearer token is used and a connection is made to our server.

**Desktop (please complete the following information):**
Ubuntu 22.04 running a `python:3.12` derived docker container

**Additional context**
I'm fairly confident the issue is with the metadata keyword argument not being passed to the appropriate grpc calls under the hood.

Let me know if you need any more info,
Thanks

**Comment by ViridianForge** [comment]
Thanks for the catch @OCDolan - could you try submitting your metadata using Tuples instead of Dictionaries? Looks like I have a typo in the example docs.

The example should read:

```
metadata = [("authorization", f"bearer {my_bearer_token}")]
client = Client.get_by_endpoint("my.supercool.hostname:443", ssl=True, metadata=metadata)
```

I'll get a correction to the docs merged shortly - but let me know if that works out for you.

**Comment by OCDolan** [comment]
Ah thanks! Unfortunately that hasn't changed anything my end, I've still got the issue. I'll do some more investigation my end and let you know if I figure it out. Thanks!

**Comment by ViridianForge** [comment]
Thanks for the follow up! I'll leave the issue open in the interim - just in case you turn something up.

**Comment by artificial-aidan** [comment]
Channel metadata isn't a keyword argument. You need to use interceptors (or credentials) to get channel metadata.

I opened a PR with support for channel interceptors, with a test example of adding channel wide metadata.

https://github.com/wesky93/grpc_requests/pull/45

**Comment by ViridianForge** [comment]
Thanks for the assists @artificial-aidan - your PRs have been merged, and will be in the next release. I'll be sending that up in the next day or so.
