### ISSUE TITLE
Requirements are stricter than they need to be

### ISSUE THREAD

**Issue by artificial-aidan** [wesky93/grpc_requests#50]
In `requirements.txt` `grpcio` and `grpcio-reflection` are pinned to `>=0.1.53`, but the code has support for older versions. I think it would make sense to set the `requirements.txt` to a less strict version. I think its probably the protobuf version that actually matters, so something like:

```
protobuf<4
grpcio
grpcio-reflection
```

**Comment by ViridianForge** [comment]
Probably fair calls - worth opening a PR and giving it a test.

**Comment by ViridianForge** [comment]
Requirements loosened up!
Thanks for calling this out @artificial-aidan!
