### ISSUE TITLE
Legacy uploading to Pypi is now deprecated

### ISSUE THREAD

**Issue by ViridianForge** [wesky93/grpc_requests#63]
@wesky93 - looks like we're going to have to work together to get the repo switched over to using api tokens to upload to pypi. The publish workflow threw the following error when I attempted to release `0.1.14`

```
25hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
         Username/Password authentication is no longer supported. Migrate to API
         Tokens or Trusted Publishers instead. See                              
         https://pypi.org/help/#apitoken and                                    
         https://pypi.org/help/#trusted-publishers                              
Error: Process completed with exit code 1.
```

**Comment by ViridianForge** [comment]
Adding a link to the [failing workflow](https://github.com/wesky93/grpc_requests/actions/runs/7436345383/job/20232688944)

**Comment by wesky93** [comment]
<img width="727" alt="2024-01-20_21-47-20" src="https://github.com/wesky93/grpc_requests/assets/5326335/fcdca62f-f219-4fb2-ac52-b2efc64e46a6">
PYPI tells me that when I deploy from the specified repository and workflow, the
OIDC to ingest deployments from specified repositories and workflows.
I don't think I'll have any token issues now, just need to change the way I build.

**Comment by wesky93** [comment]
https://github.com/wesky93/grpc_requests/actions/runs/7594698451/job/20686481766 deploy success!
